### ISSUE TITLE
Email doesn't show edited company name

### ISSUE THREAD

**Issue by Reyzelle** [vasavah/vsv-fli-pass-uat#104]
**Describe the bug**
Name of vendor used during invitation was "Laila Inc.". Vendor name was changed to "Laila Incorporated" during accreditation. When vendor was email for the accreditation, name showed was the former.

**Expected behavior**
 Email should show the correct name, if changed.

**Screenshots**
![image](https://user-images.githubusercontent.com/64526823/80583990-9d04c980-8a43-11ea-9989-f225c6312e44.png)

![image](https://user-images.githubusercontent.com/64526823/80584369-26b49700-8a44-11ea-9ff7-c9fc6423cc28.png)

**Comment by HannahCastro** [comment]
This issue is now resolved. @matthewroman for your assistance in closing ticket.
![image](https://user-images.githubusercontent.com/51902789/83604943-9c62d400-a5a9-11ea-8d34-e67e7ce61f75.png)
![image](https://user-images.githubusercontent.com/51902789/83605052-cddb9f80-a5a9-11ea-97f5-207140c6156a.png)
![image](https://user-images.githubusercontent.com/51902789/83605093-e21f9c80-a5a9-11ea-818b-7d634f8c2982.png)
