### ISSUE TITLE
Check all links for DOWNLOAD files (errors)

### ISSUE THREAD

**Issue by Reyzelle** [vasavah/vsv-fli-pass-uat#115]
**Describe the bug**
Check all links for DOWNLOAD files (errors)

**Expected behavior**
Vasavah to check if links attached to uploaded files are updated.

**Comment by HannahCastro** [comment]
This issue is resolved. @matthewroman for your assistance in closing the ticket.
![image](https://user-images.githubusercontent.com/51902789/83605919-573fa180-a5ab-11ea-8f74-a497cca6428f.png)
![image](https://user-images.githubusercontent.com/51902789/83605842-370fe280-a5ab-11ea-81db-b97be358b382.png)
