### ISSUE TITLE
Username is blank in the email sent to new users

### ISSUE THREAD

**Issue by Reyzelle** [vasavah/vsv-fli-pass-uat#120]
**Describe the bug**
Username was blank in the email for new accounts created.

**Screenshots**
![image](https://user-images.githubusercontent.com/64526823/80589129-32a45700-8a4c-11ea-8244-c6653890868b.png)

**Comment by HannahCastro** [comment]
This issue is now resolved. @matthewroman for your assistance in closing ticket.
![image](https://user-images.githubusercontent.com/51902789/83610759-8ad1fa00-a5b2-11ea-90ae-64de010c269b.png)
![image](https://user-images.githubusercontent.com/51902789/83611040-f7e58f80-a5b2-11ea-8dff-c9bbaaec8894.png)
