### ISSUE TITLE
TS 109 Open link for supplier vs. contractor / Local vs. international

### ISSUE THREAD

**Issue by zetaleona** [vasavah/vsv-fli-pass-uat#36]
•  When the vendor opened the link, it automatically redirects to the application form.
o  This should be open link > “Supplier” vs. “Contractor” > “Local” vs. “Foreign”

![29](https://user-images.githubusercontent.com/50394125/61120416-91094480-a4cf-11e9-9f15-086e0aff7272.png)

**Comment by matthewroman** [comment]
Hi Hannah, please clarify.

**Comment by HannahCastro** [comment]
It was previously discussed that when a vendor clicks on the invite link and redirects to PASS, it will show the options "Supplier" or "Contractor", then "Local" or "Foreign". Whatever options the vendor chose will redirect them to the specific application form. This is patterned after the excel application form provided by SAT.

**Comment by matthewroman** [comment]
Hi Hanna, the form automatically adjusts depending on the choices of the vendor.  Fields will automatically show/hide based on this.

**Comment by HannahCastro** [comment]
Noted. Let's just make sure that whatever requirements are for the certain category (local supplier, foreign supplier, local contractor, foreign contractor) will be in the application form. Can we make it that if a vendor chooses their country, the system tags it accordingly?

**Comment by matthewroman** [comment]
Yes we can do that.

**Comment by Lex-Castro** [comment]
> Hi Hanna, the form automatically adjusts depending on the choices of the vendor.  Fields will automatically show/hide based on this.

Hi Sir, this is okay with us. currently adjustments and choices in PASS only reflect for Local and International but not Contractor and Supplier. We have suggestions, please see image below:

![image](https://user-images.githubusercontent.com/52643156/61507168-4596ef00-aa17-11e9-8391-f32fac46a82d.png)

**Comment by Lex-Castro** [comment]
Hi Sir, in relation to adjusting fields, I would also like to lock the field 'Classification' (dropdown: local/international)

the 'Country' Field would dictate what is in 'Classification' for example, if "Philippines" then classification is "local"; otherwise "international"

regardless if the above mention is possible,

i would also like tor request that the default choice for the 'Country' Field should be "Philippines"

![image](https://user-images.githubusercontent.com/52643156/61514713-3887f900-aa33-11e9-86a8-b0e141fee9ed.png)

**Comment by Lex-Castro** [comment]
This is now resolved. This is for closing. Thanks.
