### ISSUE TITLE
Dashboard not updating

### ISSUE THREAD

**Issue by Lex-Castro** [vasavah/vsv-fli-pass-uat#46]
**Describe the bug**
Some cards in the dashboard are not updating despite the database itself is updating. We're unsure if which cards are not updating.

**To Reproduce**
1. Go to 'Dashboard'
2. Search on 'For Review and Approval Suppliers' 
3. See error: The database for For Review and Approval Suppliers updates but it doesn't reflect in the dashboard equivalent.

**Expected behavior**
The database and the dashboard are in sync in real time

**Screenshots**
![image](https://user-images.githubusercontent.com/52643156/61362636-18cac680-a8b5-11e9-9a8f-ea091998a2c5.png)

![image](https://user-images.githubusercontent.com/52643156/61362397-b671c600-a8b4-11e9-9cc8-8efa2fd69262.png)

**Comment by HannahCastro** [comment]
Dashboard is now updating. 

This is now under ticket #80 TS95: Change in vendor status doesn't include "New" tagging so this **ticket can now be closed**.
But we discovered that if a change in status was made for a vendor, no "New" tag is included. This is needed so that it appears at the top of the list. This prevents SAT to not miss out on changing of status.
Ex. AN Company was first listed as under "Ongoing Assessment". "Approve this Vendor" was clicked so status is now "For Review and Approval" but it doesn't appear at the top of the list.
![image](https://user-images.githubusercontent.com/51902789/63071500-1f9b3680-bf52-11e9-921e-baacba5ae97c.png)
Just let us know if this falls under this ticket or if we need to submit a new one.
